server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
     #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: zxg12345


mybatis:
  mapperLocations: classpath:mapper/*.xml
  #所有entity别名类所在包
  type-aliases-package: com.telecom.springcloud.entities

#eureka配置
eureka:
  client:
    #表示将自己注册到Eureak Server 默认为true
    register-with-eureka: true
    #是否从EureakServer中抓取已有的注册信息 默认为true 单节点无所谓 集群必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka, http://eureka7003:7003/eureka
      defaultZone: http://eureka7001:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #eureka 客户端向服务器发送心跳的间隔时间 默认30秒
    lease-renewal-interval-in-seconds: 1
    #eureka 服务端在接收到最后一次心跳后等待时间上限，默认90秒 超时将剔除
    lease-expiration-duration-in-seconds: 2

